
const t={
sv:{
home:"Hem",projects:"Senaste projekt",services:"Tjänster",contact:"Kontakt",
workTogether:"Låt oss jobba tillsammans",
hero:"Hemsidor som speglar ditt varumärke.",
lead:"Jag skapar personliga, moderna och professionella hemsidor för företag som vill synas, bygga förtroende och göra ett starkt första intryck online.",
work:"Se mina projekt",talk:"Skicka en förfrågan",
why:"Mer än bara en snygg hemsida.",
whyP:"Varje hemsida byggs med både känsla och funktion – så att ditt företag blir lätt att förstå, lätt att komma ihåg och lätt att kontakta.",
c1:"Personlig design",c1p:"En design som speglar ditt företag i stället för att kännas som en färdig mall.",
c2:"Mobilanpassad",c2p:"Genomtänkt design för mobil, surfplatta och dator från första början.",
c3:"Skapad för kunder",c3p:"Tydlig navigation och enkla kontaktvägar som gör nästa steg smidigt.",
cta:"Redo för en hemsida som känns rätt för ditt företag?",
ctaP:"Berätta om ditt företag och vad du vill skapa. Du behöver inte ha allt planerat innan du hör av dig.",
start:"Skicka en förfrågan",
projK:"Portfolio",projH:"Senaste projekt",
projP:"Här kommer jag att visa utvalda webbprojekt och kundcase. Nya projekt läggs till löpande.",
soon:"Kommer snart",placeholder:"Nästa projekt",
placeholderP:"Här kan jag senare lägga in projektbild, kundnamn, bransch och en kort beskrivning av projektet.",
servK:"Tjänster",servH:"Så kan jag hjälpa ditt företag.",
servP:"Webbdesign och webbutveckling för företag som vill ha en modern, tydlig och professionell hemsida.",
s1:"Webbdesign & webbutveckling",s1p:"Responsiva hemsidor utformade efter ditt varumärke, dina mål och dina kunder.",
s2:"Företagshemsidor",s2p:"Flersidiga webbplatser med tydlig struktur för tjänster, projekt, information och kontakt.",
s3:"Bokning & kontakt",s3p:"Smidiga länkar till bokning, e-post och sociala medier så att kunder enkelt kan ta nästa steg.",
s4:"Grundläggande SEO",s4p:"Semantisk struktur, metadata och en teknisk grund som hjälper Google att förstå webbplatsen.",
s5:"Underhåll",s5p:"Hjälp med mindre uppdateringar och ändringar efter lansering.",
tell:"Berätta vad du behöver",
conK:"Kontakt",conH:"Har du en idé? Jag vill gärna höra den.",
conP:"Oavsett om du behöver en helt ny hemsida eller vill utveckla din nuvarande kan du höra av dig. Berätta kort om ditt företag och vad du har i åtanke, så tar vi det därifrån.",
tip:"Du behöver inte skriva ett perfekt mejl. Ditt företagsnamn, vad du erbjuder och vad du vill ha hjälp med räcker som början.",
email:"E-post",foot:"© 2026 Grow With Asiyah. Alla rättigheter förbehållna."
},
en:{
home:"Home",projects:"Recent Projects",services:"Services",contact:"Contact",
workTogether:"Let's work together",
hero:"Websites that reflect your brand.",
lead:"I create personal, modern and professional websites for businesses that want to stand out, build trust and make a strong first impression online.",
work:"See my projects",talk:"Send an enquiry",
why:"More than just a beautiful website.",
whyP:"Every website is built with both personality and purpose – making your business easy to understand, remember and contact.",
c1:"Personal design",c1p:"A design that reflects your business instead of feeling like an off-the-shelf template.",
c2:"Mobile responsive",c2p:"Thoughtful design for phones, tablets and desktops from the very beginning.",
c3:"Built for customers",c3p:"Clear navigation and simple contact paths that make the next step easy.",
cta:"Ready for a website that feels right for your business?",
ctaP:"Tell me about your business and what you want to create. You do not need to have everything planned before reaching out.",
start:"Send an enquiry",
projK:"Portfolio",projH:"Recent Projects",
projP:"This is where I will share selected website projects and client case studies. New projects will be added over time.",
soon:"Coming soon",placeholder:"Next project",
placeholderP:"Later, I can add a project image, client name, industry and a short project description here.",
servK:"Services",servH:"How I can help your business.",
servP:"Web design and development for businesses that want a modern, clear and professional website.",
s1:"Web design & development",s1p:"Responsive websites designed around your brand, goals and customers.",
s2:"Business websites",s2p:"Multi-page websites with a clear structure for services, projects, information and contact.",
s3:"Booking & contact",s3p:"Easy links to booking, email and social media so customers can take the next step.",
s4:"Basic SEO",s4p:"Semantic structure, metadata and a technical foundation that helps Google understand your website.",
s5:"Maintenance",s5p:"Help with smaller updates and changes after launch.",
tell:"Tell me what you need",
conK:"Contact",conH:"Have an idea? I would love to hear it.",
conP:"Whether you need a completely new website or want to improve your current one, feel free to reach out. Tell me a little about your business and what you have in mind, and we can take it from there.",
tip:"You do not need to write the perfect email. Your business name, what you offer and what you need help with is enough to get started.",
email:"Email",foot:"© 2026 Grow With Asiyah. All rights reserved."
}};
function lang(l){localStorage.setItem("gwaLang",l);document.documentElement.lang=l;document.querySelectorAll("[data-t]").forEach(e=>{if(t[l][e.dataset.t])e.textContent=t[l][e.dataset.t]});document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===l))}
document.addEventListener("DOMContentLoaded",()=>{lang(localStorage.getItem("gwaLang")||"sv");document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>lang(b.dataset.lang));let m=document.querySelector(".menu"),n=document.querySelector(".nav-links");m.onclick=()=>n.classList.toggle("open")});
